Dev new2fa
chughes741/ft_transcendence pull request #73
Opened 2023-04-21 19:04 UTC by AndrePaulGrenon

Merge of Token mechanics (only really implemented with the Enable 2FA settings button for now)
Auth and 2FA working with Token from the 42 auth. Can also refresh 42 token on login if needed. 
While connecting again, QRCODE will be needed if enable2fa is on.

2023-04-22 21:24 UTC, oddtiming requested changes
Looks real good ! Needs to be formatted all over, however

2023-04-22 21:24 UTC, oddtiming commented on app/backend/src/prisma/prisma.service.ts
> +  async userNameExists(username: string): Promise<boolean> {
@AndrePaulGrenon Delete this function, as you can simply use `getUserIdByNick(nick: string)`, should be renamed to getUserIdByUsername, I'll take care of it

2023-04-22 21:24 UTC, oddtiming commented on app/backend/src/prisma/prisma.service.ts
> +  async update2FA(userName: string): Promise<boolean> {
@AndrePaulGrenon What is this?

Should be:
```
    const user = await this.user.findUnique({
      where: {
        username: userName
      },
    })
      await this.user.update({
        where: {
          username: userName
        },
        data: {
          enable2fa: !user.enable2fa
        }
      });
      return !user.enable2fa;
```

2023-04-22 21:24 UTC, oddtiming commented on app/backend/src/token-verify.ts
> +export default class TokenIsVerified implements CanActivate {
@AndrePaulGrenon Rename to FortyTwoGuard

2023-04-22 21:24 UTC, oddtiming commented on app/frontend/src/chat/chat.viewModel.tsx
> -  useEffect(() => {
Muting this might have unwanted consequences when logging in as someone else

2023-04-22 21:24 UTC, oddtiming commented on app/frontend/src/components/QrCodeElement.tsx
Needs to be formatted

2023-04-22 21:25 UTC, oddtiming commented on app/frontend/src/components/QrCodeElement.tsx
Also need to fix the build test script !
![image](https://user-images.githubusercontent.com/36460419/233807315-3464d284-a8a6-46fa-a829-48b9454a605e.png)

2023-04-23 00:19 UTC, AndrePaulGrenon commented
Closing this one

2023-04-23 00:19 UTC, closed without merging