Dev apfixes
chughes741/ft_transcendence pull request #80
Opened 2023-04-23 20:25 UTC by AndrePaulGrenon

Big cleanup, removing console log, fixing minor stuff and adding comments. Login42 ImgUpload frontend, also backen token services auth and imgtransfer. Lot cleaner.

2023-04-23 20:29 UTC, AndrePaulGrenon commented
This is just a major cleanup and some minor fixes so the auth and tokenverification is cleaner and easier to read.

2023-04-23 20:43 UTC, chughes741 commented on app/backend/src/auth/auth.service.ts
Seems to be a lot of random whitespace added. Was Prettier run before commiting?

2023-04-23 20:45 UTC, chughes741 requested changes
Run yarn format

2023-04-23 20:47 UTC, AndrePaulGrenon commented on app/backend/src/auth/auth.service.ts
Done

2023-04-23 20:47 UTC, AndrePaulGrenon commented
Yarn Format push

2023-04-25 19:40 UTC, chughes741 approved these changes

2023-04-25 19:41 UTC, merged